/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import "VoiceServices-Structs.h"
#import <Foundation/NSArray.h>


@interface NSArray (VSRecognitionSessionKeywords)
- (id)_nextKeywordUsingCursors:(CFDictionaryRef)cursors;	// 0xa2e0
- (id)_scrambledKeywordsAndAddToSet:(id)set;	// 0xa098
@end

