/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import <Foundation/NSAttributedString.h>


@interface NSAttributedString (VSSpeechAdditions)
+ (id)attributedStringWithFormatAndAttributes:(id)formatAndAttributes;	// 0x142b8
@end

