/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface VSCacheUpdateRequest : NSObject {
	NSString *_modelID;
	NSString *_classID;
}
- (id)initWithModelIdentifier:(id)modelIdentifier classIdentifier:(id)identifier;	// 0xdb94
- (id)classIdentifier;	// 0xd948
- (id)coalescedRequest:(id)request;	// 0xda3c
- (void)dealloc;	// 0xdb18
- (id)description;	// 0xd9ac
- (id)modelIdentifier;	// 0xd934
@end

