/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import "VoiceServices-Structs.h"
#import "VSRecognitionAction.h"

@class NSString, NSAttributedString, NSArray;

@interface VSRecognitionRecognizeAction : VSRecognitionAction {
	NSString *_modelIdentifier;
	NSArray *_keywords;
	void *_recognition;
	NSArray *_results;
	NSString *_debugDumpPath;
	NSString *_audioInputPath;
	double _levelInterval;
	struct {
		unsigned debugDumpEnabled : 1;
		unsigned preferredEngine : 2;
		unsigned resetEngine : 1;
		unsigned bluetoothAllowed : 1;
		unsigned hasStarted : 1;
	} _recognizeFlags;
}
@property(readonly, retain) NSString *modelIdentifier;	// G=0xc44c; 
- (id)initWithModelIdentifier:(id)modelIdentifier;	// 0xc8d0
- (id)_actionForEmptyResults;	// 0xc4cc
- (void)_configureNewRecognitionInstance;	// 0xcf54
- (void)_continueAfterDeferredStart;	// 0xc6d0
- (VSRecognitionRef)_createRecognitionInstanceWithCallbacks:(XXStruct__Vsh7C *)callbacks info:(void *)info;	// 0xcf08
- (id)_debugDumpPath;	// 0xc4b8
- (void)_handleRecognitionCompleted:(VSRecognitionRef)completed withResults:(CFArrayRef)results error:(CFErrorRef)error;	// 0xd34c
- (void)_handleRecognitionPrepared:(VSRecognitionRef)prepared;	// 0xc5f4
- (void)_handleRecognitionStarted:(VSRecognitionRef)started;	// 0xc4d4
- (void)_handledThreadedResults:(id)results nextAction:(id)action;	// 0xc598
- (BOOL)_hasDeferredStartCallback;	// 0xc460
- (float)_inputLevel;	// 0xcb9c
- (BOOL)_isActivelyRecognizing;	// 0xcab0
- (BOOL)_isRecognizing;	// 0xcae4
- (id)_keywordAtIndex:(int)index;	// 0xc7b8
- (int)_keywordCount;	// 0xc78c
- (BOOL)_keywordIndexChanged;	// 0xc740
- (id)_keywords;	// 0xc810
- (void)_releaseFromPrepare;	// 0xd2c8
- (void)_reset;	// 0xc920
- (BOOL)_setAudioInputPath:(id)path;	// 0xcdd0
- (BOOL)_setBluetoothInputAllowed:(BOOL)allowed;	// 0xc468
- (BOOL)_setDebugDumpEnabled:(BOOL)enabled;	// 0xc718
- (BOOL)_setDebugDumpEnabled:(BOOL)enabled dumpPath:(id)path;	// 0xcbec
- (BOOL)_setDebugDumpPath:(id)path;	// 0xc6ec
- (BOOL)_setEngineResetRequired:(BOOL)required;	// 0xce80
- (BOOL)_setInputLevelUpdateInterval:(double)interval;	// 0xcb38
- (BOOL)_setPreferredEngine:(int)engine;	// 0xcd48
- (void)_setResults:(id)results;	// 0xc674
- (id)cancel;	// 0xd244
- (int)completionType;	// 0xc444
- (void)dealloc;	// 0xc9c0
- (id)perform;	// 0xd124
@end

