/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import "VSRecognitionRecognizeAction.h"

@class NSString, NSAttributedString;

@interface VSRecognitionConfirmAction : VSRecognitionRecognizeAction {
	VSRecognitionAction *_confirmedAction;
	VSRecognitionAction *_deniedAction;
	struct {
		unsigned initializing : 1;
		unsigned confirmed : 1;
	} _confirmFlags;
}
@property(retain) VSRecognitionAction *confirmedAction;	// G=0x10384; S=0x105ac; 
@property(retain) VSRecognitionAction *deniedAction;	// G=0x10398; S=0x10550; 
- (id)init;	// 0x104a8
- (id)initWithModelIdentifier:(id)modelIdentifier;	// 0x10434
- (void)_setConfirmed:(BOOL)confirmed;	// 0x10360
- (int)completionType;	// 0x103ac
- (void)dealloc;	// 0x10608
@end

