/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import "VSRecognitionAction.h"

@class NSString, NSAttributedString, NSURL;

@interface VSRecognitionURLAction : VSRecognitionAction {
	NSURL *_url;
}
@property(retain) id URL;	// G=0x10eac; S=0x10ec0; 
- (int)completionType;	// 0x10ea4
- (void)dealloc;	// 0x10f1c
- (id)perform;	// 0x10f7c
@end

