/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import <Foundation/NSObject.h>

@class NSConditionLock, NSMutableArray;
@protocol VSRecognitionResultHandlingThreadDelegate;

@interface VSRecognitionResultHandlingThread : NSObject {
	id<VSRecognitionResultHandlingThreadDelegate> _delegate;
	NSMutableArray *_requests;
	NSConditionLock *_lock;
	struct {
		unsigned running : 1;
		unsigned delegateDidHandleResults : 1;
		unsigned valid : 1;
	} _resultHandlingFlags;
}
- (id)init;	// 0x131f4
- (void)_handleRequests;	// 0x12b6c
- (void)_notifyRequestHandled:(id)handled;	// 0x12e74
- (void)dealloc;	// 0x13178
- (void)handleResults:(id)results withHandler:(id)handler;	// 0x12f90
- (void)invalidate;	// 0x12f14
- (void)setDelegate:(id)delegate;	// 0x1310c
@end

