/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import <Foundation/NSObject.h>

@class NSArray, VSRecognitionAction;
@protocol VSRecognitionResultHandler;

@interface VSRecognitionResultHandlingRequest : NSObject {
	id<VSRecognitionResultHandler> _handler;
	NSArray *_results;
	VSRecognitionAction *_action;
}
@property(retain) id nextAction;	// G=0x1294c; S=0x12988; 
@property(readonly, retain) NSArray *results;	// G=0x12a20; 
- (id)initWithHandler:(id)handler results:(id)results;	// 0x12af0
- (void)dealloc;	// 0x12a5c
- (id)handler;	// 0x129e4
@end

