/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import "VoiceServices-Structs.h"
#import "VSRecognitionRecognizeAction.h"

@class NSString, NSMutableDictionary;

@interface VSRecognitionDisambiguateAction : VSRecognitionRecognizeAction {
	NSString *_repeatedSpokenFeedbackString;
	NSString *_sequenceTag;
	NSMutableDictionary *_knownValues;
	NSMutableDictionary *_knownPhoneticValues;
	NSMutableDictionary *_ambiguousValues;
	NSMutableDictionary *_ambiguousPhoneticValues;
	void *_context;
}
@property(retain) NSString *repeatedSpokenFeedbackString;	// G=0xb728; S=0xbee4; 
@property(retain) NSString *sequenceTag;	// G=0xb73c; S=0xbe88; 
- (id)_actionForEmptyResults;	// 0xb758
- (VSRecognitionRef)_createRecognitionInstanceWithCallbacks:(XXStruct__Vsh7C *)callbacks info:(void *)info;	// 0xc3ac
- (VSRecognitionDisambiguationContextRef)_disambiguationContext;	// 0xc248
- (BOOL)_keywordIndexChanged;	// 0xb750
- (id)_keywords;	// 0xc038
- (id)ambiguousValuesForClassIdentifier:(id)classIdentifier;	// 0xba10
- (int)completionType;	// 0xb720
- (void)dealloc;	// 0xbf40
- (id)knownValueForClassIdentifier:(id)classIdentifier;	// 0xbe00
- (id)knownValuesForClassIdentifier:(id)classIdentifier;	// 0xbbd4
- (void)setAmbiguousValues:(id)values phoneticValues:(id)values2 forClassIdentifier:(id)classIdentifier;	// 0xb890
- (void)setKeywords:(id)keywords;	// 0xb7c4
- (void)setKnownValue:(id)value phoneticValue:(id)value2 forClassIdentifier:(id)classIdentifier;	// 0xbc68
- (void)setKnownValues:(id)values phoneticValues:(id)values2 forClassIdentifier:(id)classIdentifier;	// 0xba3c
@end

