/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import "VoiceServices-Structs.h"
#import <Foundation/NSObject.h>

@class NSString;
@protocol VSSpeechSynthesizerDelegate;

@interface VSSpeechSynthesizer : NSObject {
@private
	void *_speechJob;
	void *_keepAlive;
	id<VSSpeechSynthesizerDelegate> _delegate;
	NSString *_voice;
	float _rate;
	float _pitch;
	float _volume;
	struct {
		unsigned delegateStart : 1;
		unsigned delegateFinish : 1;
		unsigned delegatePause : 1;
		unsigned delegateContinue : 1;
		unsigned delegateWillSpeak : 1;
		unsigned willUseInput : 1;
	} _synthesizerFlags;
}
@property(readonly, assign) float pitch;	// G=0xeb30; 
@property(readonly, assign) float rate;	// G=0xeb04; 
@property(retain) NSString *voice;	// G=0xef50; S=0xefd0; 
@property(readonly, assign) float volume;	// G=0xeb48; 
+ (void)_localeDidChange;	// 0xef14
+ (id)availableLanguageCodes;	// 0xfcfc
+ (id)availableVoices;	// 0xfc54
+ (id)availableVoicesForLanguageCode:(id)languageCode;	// 0xfcc8
+ (BOOL)isSystemSpeaking;	// 0xfd1c
- (id)init;	// 0xeb60
- (id)initForInputFeedback;	// 0xf2cc
- (void)_handleSpeech:(VSSpeechRef)speech completed:(BOOL)completed withError:(id)error;	// 0xf308
- (void)_handleSpeech:(VSSpeechRef)speech willSpeakMarkType:(int)type inRange:(XXStruct_K5nmsA)range;	// 0xed6c
- (void)_handleSpeechContinued:(VSSpeechRef)continued;	// 0xede8
- (void)_handleSpeechPaused:(VSSpeechRef)paused;	// 0xee4c
- (void)_handleSpeechStarted:(VSSpeechRef)started;	// 0xeeb0
- (id)continueSpeaking;	// 0xfabc
- (void)dealloc;	// 0xf3ac
- (BOOL)isSpeaking;	// 0xfb4c
- (float)maximumRate;	// 0xeb24
- (float)minimumRate;	// 0xeb1c
- (id)pauseSpeakingAtNextBoundary:(int)nextBoundary;	// 0xf02c
- (id)pauseSpeakingAtNextBoundary:(int)nextBoundary synchronously:(BOOL)synchronously;	// 0xfa18
- (void)setDelegate:(id)delegate;	// 0xf18c
- (void)setMaintainPersistentConnection:(BOOL)connection;	// 0xfbb8
- (id)setPitch:(float)pitch;	// 0xf454
- (id)setRate:(float)rate;	// 0xf4f4
- (id)setVolume:(float)volume;	// 0xf594
- (id)speechString;	// 0xfb80
- (id)startSpeakingAttributedString:(id)string;	// 0xf0e0
- (id)startSpeakingAttributedString:(id)string toURL:(id)url;	// 0xf0a8
- (id)startSpeakingAttributedString:(id)string toURL:(id)url withLanguageCode:(id)languageCode;	// 0xf06c
- (id)startSpeakingString:(id)string;	// 0xf160
- (id)startSpeakingString:(id)string attributedString:(id)string2 toURL:(id)url withLanguageCode:(id)languageCode;	// 0xf694
- (id)startSpeakingString:(id)string toURL:(id)url;	// 0xf134
- (id)startSpeakingString:(id)string toURL:(id)url withLanguageCode:(id)languageCode;	// 0xf100
- (id)stopSpeakingAtNextBoundary:(int)nextBoundary;	// 0xf04c
- (id)stopSpeakingAtNextBoundary:(int)nextBoundary synchronously:(BOOL)synchronously;	// 0xfd30
@end

