/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import "VoiceServices-Structs.h"
#import <Foundation/NSObject.h>

@class NSString;

@interface VSTextPreProcessorRule : NSObject {
	NSString *_matchPattern;
	NSString *_replacement;
	BOOL _caseSensitive;
	BOOL _eatPunctuation;
}
- (id)initWithDictionaryRepresentation:(id)dictionaryRepresentation;	// 0x138e8
- (void)dealloc;	// 0x13a78
- (id)matchedString:(id)string forTokenInRange:(XXStruct_K5nmsA *)range;	// 0x13af4
@end

