/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import <Foundation/NSObject.h>
#import "VoiceServices-Structs.h"

@class NSArray, NSString;

@interface VSTextPreProcessor : NSObject {
	NSArray *_rules;
	NSString *_languageID;
	CFStringTokenizerRef _tokenizer;
}
- (id)initWithContentsOfPath:(id)path languageIdentifier:(id)identifier;	// 0x13294
- (void)dealloc;	// 0x1357c
- (id)processedTextFromString:(id)string;	// 0x13614
@end

